### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by amebrahimi** [vandadnp/youtube-course-rxdart#1]
Hello, 
Thanks for this lovely tutorial.
Sorry but when I was checking this repo I noticed you didn't pushed your tags to the github. 
😊

**Comment by vandadnp** [comment]
Hi, thank you for bringing this up to me. I have now pushed the tags and they are available here: https://github.com/vandadnp/youtube-course-rxdart/tags

**Comment by amebrahimi** [comment]
I'm glad that I found your channel on youtube.
You are good at explaining things.
